import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Headers from '../components/Headers'
import 'bootstrap/dist/css/bootstrap.min.css';
import Footer from '../components/Footer'
import About from '../components/About'
import Contact from '..//components/Contact'
import Jumbotron from '../components/Jumbo'
import Quemsomos from '../components/Quemsomos'
import Comosomos from '../components/Comosomos'
import Servicos from '../components/Servicos'

export default function Home() {
  return (

    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Headers/>
      <Quemsomos/>
      <Comosomos/>
      <Servicos/>
      <Jumbotron/>
      <About/>
      <Contact/>
    
      
      

      <main className={styles.main}>  

      </main>  
      <Footer/>
   
    </div>
  )
}
