import { useState, useEffect } from 'react'
import Head from 'next/head'
import Headers from '../components/Headers'
import 'bootstrap/dist/css/bootstrap.min.css';
import Footer from '../components/Footer'
import Link from 'next/link'



export default function Noticias() {
  const [error, setError] = useState(null);
  const [isLoaded, setIsLoaded] = useState(false);
  const [items, setItems] = useState([]);

  // Nota: O array [] deps vazio significa
  // este useEffect será executado uma vez
  // semelhante ao componentDidMount()

  
  

  const url = "https://bing-news-search1.p.rapidapi.com/news?count=10&cc=Ultimas%20Noticias&setLang=pt&safeSearch=Off&textFormat=Raw"



  const req = new Request(url);

  useEffect(() => {
    fetch(req, {
	"method": "GET",
	"headers": {
		"accept-language": "br",
		"x-bingapis-sdk": "true",
		"x-search-location": "br",
		"x-rapidapi-host": "bing-news-search1.p.rapidapi.com",
		"x-rapidapi-key": "e9970d4199msh61cd785b8750db9p1d9d1djsnca008e95cb75"
	}
})     
      .then(res => res.json())
      .then(
        (result) => {
          setIsLoaded(true);
          setItems(result.value);
        },
        // Nota: é importante lidar com errros aqui
        // em vez de um bloco catch() para não receber
        // exceções de erros reais nos componentes.
        (error) => {
          setIsLoaded(true);
          setError(error);
        }
      )
  }, [], console.log("resultado do get", items))


  if (error) {
    return <div>Error: {error.message}</div>;
  } else if (!isLoaded) {
    return <div>Loading...</div>;
  } else {
    return (

      <div>
        <Head>
          <title>Radio MCR Web</title>
          <meta name="description" content="Generated by create app web radio MCR" />
          <link rel="icon" href="/logo.png" />
        </Head>
        <Headers />

        <div className="container-fluid"> 

        

        <div  className="container-noticia">
        <h1 className="text-center pb-5"> Ultimas Noticias</h1>
          {items.map(item => (
            <div key={item.id} className="div-noticia">
              <header>
                <a className="a-titulo" href={item.url} target="_blank" rel="noreferrer"><h3>{item.name}</h3></a>                              
                <p className="data-public">{item.datePublished}</p>
              </header>
              <div className="row g-2">
              <div className="col-sm-3">
                <img className="img-noticia" src={item.image.thumbnail.contentUrl} />
              </div>

              <div className="col m-0"> 
                <p className="p-description">{item.description}</p>
              </div>

              </div>
             
            </div>
          ))}

        </div>
        <Footer/>

      </div>
        </div>

    );
  }
}