import { useState, useEffect } from 'react'
import Head from 'next/head'
import Headers from '../components/Headers'
import 'bootstrap/dist/css/bootstrap.min.css';
import Footer from '../components/Footer'



export default function Noticias() {
  const [error, setError] = useState(null);
  const [isLoaded, setIsLoaded] = useState(false);
  const [items, setItems] = useState([]);

  // Nota: O array [] deps vazio significa
  // este useEffect será executado uma vez
  // semelhante ao componentDidMount()
  const url = 'https://newsapi.org/v2/top-headlines?sources=google-news-br&apiKey=de3e556815064e36b659f605189029d9';

  const req = new Request(url);

  useEffect(() => {
    fetch(req)
      .then(res => res.json())
      .then(
        (result) => {
          setIsLoaded(true);
          setItems(result.articles);
        },
        // Nota: é importante lidar com errros aqui
        // em vez de um bloco catch() para não receber
        // exceções de erros reais nos componentes.
        (error) => {
          setIsLoaded(true);
          setError(error);
        }
      )
  }, [], console.log("resultado do get", items))


  if (error) {
    return <div>Error: {error.message}</div>;
  } else if (!isLoaded) {
    return <div>Loading...</div>;
  } else {
    return (

      <div>
        <Head>
          <title>Radio MCR Web</title>
          <meta name="description" content="Generated by create app web radio MCR" />
          <link rel="icon" href="/logo.png" />
        </Head>
        <Headers />

        <div  className="container">
          {items.map(item => (
            <div key={item.id}>
              <header>
                <h1>{item.title}</h1>
                <h4>{item.description}</h4>
                <h5>{item.publishedAt}</h5>
              </header>
              <main>
                <img src={item.urlToImage} />
                <p>{item.content}</p>
                <p>Confira a materia completa <a>{item.url}</a></p>
              </main>
            </div>
          ))}

        </div>
        <Footer/>

      </div>
    );
  }
}